name: Publish personal portfolio

on:
   push:
      branches: [gh-pages]

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - uses: enriikke/gatsby-gh-pages-action@v2.1.1
           with:
              access-token: ${{ secrets.MY_ONLINE_PORTFOLIO }}
              deploy-branch: master
